### PR TITLE
Add DisplayName and Description to Windows service

### LINKED ISSUE #99: The wmi_exporter service should have a description
Hi,

The wmi_exporter service should have a description, and the display name could possibly be changed to something more friendly, for example "Prometheus WMI exporter".

Thank you

### PR DESCRIPTION
**Pull request by carlpett**
Fixes #99.

I opted to set the display name to just "WMI Exporter" rather than the arguable clearer "Prometheus WMI exporter" to avoid throwing people off who might be used to it being called wmi_exporter in the list. Opinions? Maybe too change-averse? :)

@lubyou

### CODE REVIEW

**Comment by martinlindhe** [comment]
LGTM!

**Comment by lubyou** [comment]
Hi,

I personally prefer "Prometheus WMI Exporter", as I believe that prefixing services with the org/company name makes it easier to differentiate them from the MS services (which are not prefixed).

**Comment by martinlindhe** [comment]
All of Microsoft's services have the Company name set, which allows you to find this out.

Screenshot lacks this PR, but shows the company name field of their services:

untitled

**Comment by lubyou** [comment]
Hi,

What I meant is to have the company name as part of the display name, as HP, Symantec, Veeam, VMware and others seem to do for their services, as opposed to the company name in the StringFileInfo.

On numerous occasions, I sorted services in services.msc by display name to look for services from a specific vendor, where the fact that the vendor included its name in the display name was helpful.

Ultimately I am fine with either "WMI Exporter" or "Prometheus WMI Exporter", it is just a name, and ultimately the functionality is what counts, but I still believe that including "Prometheus" into the display name is useful to people who use services.msc.

**Comment by martinlindhe** [comment]
> What I meant is to have the company name as part of the display name, as HP, Symantec, Veeam, VMware and others seem to do for their services, as opposed to the company name in the StringFileInfo.

Yes, I understand that.
However this does not appear to be standard as I mentioned earlier, and you would be better off sorting on the Company Name.

The thing is, we are a separate project and currently not part of Prometheus more than compatible by them. We love prometheus but we also have no right to use their name.

**Comment by brian-brazil** [comment]
Using Prometheus as a descriptor is not a problem, so you could do "WMI Exporter for Prometheus" for example.

**Comment by martinlindhe** [comment]
@brian-brazil thanks. That sounds like a good solution

What do you think @lubyou ?

**Comment by lubyou** [comment]
I am still in favour of "Prometheus WMI Exporter", because of the sorting thing (I can sort processes by company name,  but not services)

Your call :)

**Comment by martinlindhe** [comment]
"WMI exporter for Prometheus" implies we are compatible with Prometheus.
"Prometheus WMI exporter" implies we ARE Prometheus.

This is starting to become major bikeshedding...

Let @carlpett decide on final wording

**Pull request merged**
