### PR TITLE
add boilerplate for promu

### PR DESCRIPTION
**Pull request by martinlindhe**
For this to be usable, https://github.com/prometheus/promu/pull/47 needs to land first

This excludes setting BuildUser. I dont see it is useful. Thought?

### CODE REVIEW

**Comment by carlpett** [comment]
Hm. Kluven.
Here are some potential benefits, though their actual value can be contested:
1. It would help point out that a binary was built somewhere else than AppVeyor, ie may not be consistent with any particular state in the repo
2. The version output will still contain a user field, so not populating it will "look odd"
3. "Might as well for consistency"

Yup, not very good ones, but it's what I've got.

**Comment by martinlindhe** [comment]
Okay all good points!
I re-added it and squashed commit.
Personally i feel it's too much info (user@host), but no big deal since appveyor will build binaries for us anyway.

**Comment by carlpett** [comment]
Now that the promu change is merged, this just needs a bump to govendor and then we're good to release 0.1, right?

**Comment by martinlindhe** [comment]
yep, think so! should we try to finish up 0.1 today (merge this pr and bump vendor), and maybe post a little announcement tomorrow or so? any objections?

**Comment by carlpett** [comment]
@martinlindhe Sorry, been away a while. Yes, I think that sounds excellent!

**Comment by martinlindhe** [comment]
@carlpett no worries, welcome back!

**Pull request merged**
