### PR TITLE
adding windows service example alerts/queries

### PR DESCRIPTION
**Pull request by chrisbloemker**
Just contributing some useful examples that I have made using for monitoring Microsoft SQL Server instances.

### CODE REVIEW

**Comment by carlpett** [comment]
Thanks a lot @chrisbloemker!
Just out of curiousity, you seem to have a non-standard labeling scheme with regards to setting the `name` label everywhere?

**Comment by chrisbloemker** [comment]
Ahh, yes.. the way we have Prometheus setup for our ec2 scraping is the instance id is relabeled as `instance`, leaving the tag "Name" to be relabeled as `name` I can change the PR to reflect the examples to be more standardized if you'd like.

**Comment by carlpett** [comment]
Yes, I think that would be good, probably less confusing that way. Thanks!

**Comment by chrisbloemker** [comment]
Done :)

**Comment by carlpett** [comment]
Thanks!

**Pull request merged**
