### PR TITLE
fix mssql for non-default sql instances

### PR DESCRIPTION
**Pull request by szook**
the only sql servers I have access to are using the default
`MSSQLSERVER` instance names.  I was contacted by someone using a
different instance name and it was failing.

Found 2 bugs in the code:

1) I was returning the default `MSSQLSERVER` as an instance even if it wasn't found in the registry

2) learned that the WMI class naming scheme for non-default instances
was not what I had coded. Changed to incorproate new knowledge.

### CODE REVIEW

**Comment by szook** [comment]
work in progress until the `AccessMethods` change is merged and I can rebase.

**Comment by carlpett** [comment]
#236 is merged!

**Comment by carlpett** [comment]
LGTM, anything apart from rebase needed?

**Comment by szook** [comment]
I'm also working offline with @sysadmind to see if this, indeed, works.

**Comment by szook** [comment]
got confirmation that this works.  Removed WIP

**Comment by carlpett** [comment]
Thanks! Cutting a new release in a few minutes

**Pull request merged**
