### PR TITLE
vendor dependencies using govendor, fixes #16

### LINKED ISSUE #16: Use govendor?
(see #15 for previous discussion)

### PR DESCRIPTION
**Pull request by martinlindhe**
@carlpett

### CODE REVIEW

**Comment by carlpett** [comment]
Looks good!

**Comment by martinlindhe** [comment]
ran 
```
govendor init
govendor list
govendor fetch <once for each external depencency>
```

resulting in

```
$ govendor list
 v  github.com/StackExchange/wmi
 v  github.com/beorn7/perks/quantile
 v  github.com/go-ole/go-ole
 v  github.com/go-ole/go-ole/oleutil
 v  github.com/golang/protobuf/proto
 v  github.com/matttproud/golang_protobuf_extensions/pbutil
 v  github.com/prometheus/client_golang/prometheus
 v  github.com/prometheus/client_model/go
 v  github.com/prometheus/common/expfmt
 v  github.com/prometheus/common/internal/bitbucket.org/ww/goautoneg
 v  github.com/prometheus/common/model
 v  github.com/prometheus/procfs
 e  github.com/martinlindhe/wmi_exporter/collector
pl  github.com/martinlindhe/wmi_exporter
```

**Comment by martinlindhe** [comment]
I'm new to using govendor, is the "e" (external) dep on github.com/martinlindhe/wmi_exporter/collector a problem? I dont want to vendor code from this repo, feels too much like Inception for my liking

**Comment by martinlindhe** [comment]
got some build fail from appveyor, and just left work. will have a look at it tomorrow

**Comment by carlpett** [comment]
Hm, no, we should not vendor ourselves :) I haven't used govendor either, only godeps, but I'll try to have a look at the documentation

**Comment by martinlindhe** [comment]
sorted out the govendor stuff, and added a VENDOR.md with some notes.

long story short: updated build instructions from "go build" to "govendor build +local" + added a missing dependency. tested with a empty GOPATH. also updated appveyor.yml

**Comment by carlpett** [comment]
Great work! Regarding the external flagging of `wmi_exporter/collector`, I think this may be related? https://github.com/kardianos/govendor/issues/209

**Comment by martinlindhe** [comment]
Indeed looks like the same bug, good find!

**Comment by martinlindhe** [comment]
The govendor-on-windows bug is fixed: https://github.com/kardianos/govendor/pull/216

**Pull request merged**
