### PR TITLE
Add container collector doc link to readme

### PR DESCRIPTION
**Pull request by Drewster727**

### CODE REVIEW

**Comment by carlpett** [comment]
Hey @Drewster727,
Thanks, this looks good to me!

**Comment by carlpett** [comment]
@Drewster727 I just realized that we have the labels listed in the docs - could you please open a new PR to add `container_name` there? Thanks!

**Comment by Drewster727** [comment]
@carlpett absolutely I can do that. However, I'm hesitant to call that "good to go" as the container name is just the container ID, which isn't very helpful IMO. It's not really providing the name from a docker perspective, and I can't determine if there's a way to provide the name of the image the container is running on. Any thoughts?

**Comment by carlpett** [comment]
Huh, I assumed from the docs that this would do that... Premature merge then, perhaps.
I opened [hcsshim/#652](https://github.com/microsoft/hcsshim/issues/652) to see if this is intentional.

**Comment by simmohall** [comment]
Hi guys,
I ran into the same issue of having the containerId being useless and the hcsshim Name property not being the useful container name.
I ended up having to use the library github.com/docker/docker/client to get the actual container name. (didn't create a PR as i'm not sure it's the best way to do it and I've never used GO :))
btw - awesome exporter guys, really making good use of it

**Comment by carlpett** [comment]
@Drewster727 I think we'll need to revert this until we've closed the discussion in #357 :cry:

**Pull request merged**
