### PR TITLE
Logical disk latency metrics

### PR DESCRIPTION
**Pull request by manohrn**

### CODE REVIEW

**Comment by carlpett** [comment]
Hi @manohrn,
Thanks for the contribution! This overlaps with #329, and the same comments that I mentioned there are relevant to your patch as well.

**Comment by manohrn** [comment]
Can you please help me to get the wmi exporter.msi  Which has BELOW METRICS.
AvgDiskSecPerRead
AvgDiskSecPerWrite

**Comment by carlpett** [comment]
There is no MSI with those metrics, since the mentioned PR is not merged. This is because it has some issues, which also exist in your PR. If you could make those fixes to your PR, we can merge it.

The changes needed are:
- The metric names should show that it is total time spent in each operation, so `read_latency_seconds_total`, `write_latency_seconds_total` and `read_write_latency_seconds_total`.
-  Your PR additionally needs to be rebased in order to be mergeable.

**Comment by carlpett** [comment]
Replaced by #387

**Pull request closed without merging**
