### PR TITLE
Implement IIS worker process and server cache classes

### LINKED ISSUE #85: Feature Request: IIS HTTP Status
Hi,

I have a feature request to extend the WMI Exporter to expose metrics capturing the following:

- The total amount of 4** HTTP Status return codes received from a site for a given HTTP call 

- The total amount of 5** HTTP status return codes received from a site for a given HTTP call

I know at the moment you expose the total amount of HTTP calls for a given type e.g GET. I was thinking it would be good to see something like the following:

wmi_iis_requests_total{method="GET",site="ExampleSite",status="5**"} 

Additionally, I think it would be useful to extend the current IIS exporter to include these metrics in order to get throughput metrics:

BytesSentPerSec
BytesReceivedPerSec
BytesTotalPerSec

which is already included as part of the Win32_PerfRawData_W3SVC_WebService

Apologies if you have this available already!

Cheers

### PR DESCRIPTION
**Pull request by carlpett**
Fixes #85.

This became a pretty large patch, which also involved a fair amount of copy/paste to restructure all the cache metrics. I _think_ I caught all of them, but would appreciate a careful look.
The collector is also getting quite big. We should consider having a way of splitting it into sub-collectors so it is not as unwieldy to navigate (from an end user perspective I don't think you'd want to switch parts on/off, so we should still have them all toggled by the `iis` flag).

Some previous changes seems to have been done without `go fmt`, so there are a few whitespace changes in unrelated parts as well.

### CODE REVIEW

**Comment by martinlindhe** [comment]
LGTM!
Regarding splitting the code up, sounds good too. Ive no iis server up to test this on at the moment, but since it is just additions, it should be safe.

Would be great if @jazzhanns could give it a try

**Comment by martinlindhe** [comment]
Regarding gofmt, we could set up a build step in travis to force it to pass gofmt for the future. But I am not sure it is so contributor-friendly. Might be better if we gofmt manually now and then. I committed a Makefile with a fmt target ("make fmt") to run gofmt on the source

**Comment by carlpett** [comment]
Yes, let's try to figure out a good structure for "big" collectors separate from this PR. After building this, I feel like it might be good to give some testing a thought as well. Esp when we combine multiple similarly named counters in different ways... Will likely result in bugs sooner or later. Again, out of scope for this PR, but we should keep it in mind for a rainy day (good thing we have lots of those during our summers, eh? ;) )

@jazzhanns, if you could test the PR build, that would be very appreciated as mentioned. Here is a download link: https://ci.appveyor.com/api/buildjobs/l5yanrcowve0ev3w/artifacts/wmi_exporter-amd64.zip

**Comment by jazzhanns** [comment]
Hi all, apologies for being late on this! I was away on holiday - will hopefully have a chance to test this out this afternoon and will let you know if there are any issues etc.

Cheers! :)

**Comment by jazzhanns** [comment]
Hi all,

I downloaded the exe and I wasn't able to pull back any IIS metrics at all :( 

Just wanted to give you a quick update. 

Cheers!

**Comment by carlpett** [comment]
@jazzhanns That is _very_ strange. Do you get any errors logged?

**Comment by jazzhanns** [comment]
@carlpett No, nothing! From the server point of view of the exporter it seemed to be behaving normally. I double checked that it wasn't an issue with my local box but when I started the original wmi_exporter instance it seemed to work again and I could pull the metrics back.

**Comment by carlpett** [comment]
Hm, odd. It works on my machine (tm). Do you get a collector error? (`wmi_exporter_scrape_duration_seconds_count{collector="iis"}`, do you have any `result="failed"`?)

Could you try starting with `-log-level debug` and see if that gives any more output? Are you running this in a console or as a service?

**Comment by jazzhanns** [comment]
Had a quick look at the wmi_exporter_scrape_duration_seconds_count{collector="iis"} and it's not appearing in the list as a collector at all :S

**Comment by jazzhanns** [comment]
Hello, I also set the logs to debug but again - nothing is showing for the IIS collector at all. I even restarted my IIS just to check that it wasn't the issue but still nothing coming up.

**Comment by carlpett** [comment]
How are you starting the exporter? What flags?

**Comment by jazzhanns** [comment]
Hi - Sorry, I realised I forgot to enable the IIS collector on startup (I blame post-holiday blues). The Collector is now turning up with the original metrics though it says: wmi_exporter_scrape_duration_seconds_count{collector="iis",result="error"} - and I cannot see any of the new metrics appearing in the list. Running in debug mode it gives me a list of invalid queries being returned to me thrown by the IIS collector. Though it doesn't explicitly state what this invalid query is.

**Comment by carlpett** [comment]
Ok. What versions of Windows and IIS are you running? Could you run `gwmi Win32_PerfRawData_W3SVCW3WPCounterProvider_W3SVCW3WP | gm | select -ExpandProperty name` and `gwmi Win32_PerfRawData_W3SVC_WebServiceCache | gm | select -ExpandProperty name` in a powershell prompt and paste the output here?

**Comment by jazzhanns** [comment]
Windows Version: Windows Server 2008
IIS Version: 7.5


Results of First Call:

PSComputerName
ActiveFlushedEntries
ActiveRequests
ActiveThreadsCount
Caption
CurrentFileCacheMemoryUsage
CurrentFilesCached
CurrentMetadataCached
CurrentURIsCached
Description
FileCacheFlushes
FileCacheHits
FileCacheHitsPersec
FileCacheMisses
FileCacheMissesPersec
Frequency_Object
Frequency_PerfTime
Frequency_Sys100NS
MaximumFileCacheMemoryUsage
MaximumThreadsCount
MetadataCacheFlushes
MetadataCacheHits
MetadataCacheHitsPersec
MetadataCacheMisses
MetadataCacheMissesPersec
Name
OutputCacheCurrentFlushedItems
OutputCacheCurrentItems
OutputCacheCurrentMemoryUsage
OutputCacheHitsPersec
OutputCacheMissesPersec
OutputCacheTotalFlushedItems
OutputCacheTotalFlushes
OutputCacheTotalHits
OutputCacheTotalMisses
RequestsPerSec
Timestamp_Object
Timestamp_PerfTime
Timestamp_Sys100NS
TotalFilesCached
TotalFlushedFiles
TotalFlushedMetadata
TotalFlushedURIs
TotalHTTPRequestsServed
TotalMetadataCached
TotalThreads
TotalURIsCached
URICacheFlushes
URICacheHits
UriCacheHitsPersec
URICacheMisses
UriCacheMissesPersec
__CLASS
__DERIVATION
__DYNASTY
__GENUS
__NAMESPACE
__PATH
__PROPERTY_COUNT
__RELPATH
__SERVER
__SUPERCLASS
ConvertFromDateTime
ConvertToDateTime


Results of second call

PSComputerName
ActiveFlushedEntries
Caption
CurrentFileCacheMemoryUsage
CurrentFilesCached
CurrentMetadataCached
CurrentURIsCached
Description
FileCacheFlushes
FileCacheHits
FileCacheHitsPercent
FileCacheHitsPercent_Base
FileCacheMisses
Frequency_Object
Frequency_PerfTime
Frequency_Sys100NS
KernelCurrentURIsCached
KernelTotalFlushedURIs
KernelTotalURIsCached
KernelURICacheFlushes
KernelURICacheHits
KernelURICacheHitsPercent
KernelURICacheHitsPercent_Base
KernelUriCacheHitsPersec
KernelURICacheMisses
MaximumFileCacheMemoryUsage
MetadataCacheFlushes
MetadataCacheHits
MetadataCacheHitsPercent
MetadataCacheHitsPercent_Base
MetadataCacheMisses
Name
OutputCacheCurrentFlushedItems
OutputCacheCurrentHitsPercent
OutputCacheCurrentHitsPercent_Base
OutputCacheCurrentItems
OutputCacheCurrentMemoryUsage
OutputCacheTotalFlushedItems
OutputCacheTotalFlushes
OutputCacheTotalHits
OutputCacheTotalMisses
Timestamp_Object
Timestamp_PerfTime
Timestamp_Sys100NS
TotalFilesCached
TotalFlushedFiles
TotalFlushedMetadata
TotalFlushedURIs
TotalMetadataCached
TotalURIsCached
URICacheFlushes
URICacheHits
URICacheHitsPercent
URICacheHitsPercent_Base
URICacheMisses
__CLASS
__DERIVATION
__DYNASTY
__GENUS
__NAMESPACE
__PATH
__PROPERTY_COUNT
__RELPATH
__SERVER
__SUPERCLASS
ConvertFromDateTime
ConvertToDateTime

**Comment by carlpett** [comment]
Ah. That is an older version than I have had available for testing. There are some properties that are missing on your system:

```
Percent401HTTPResponseSent
Percent403HTTPResponseSent
Percent404HTTPResponseSent
Percent500HTTPResponseSent
WebSocketActiveRequests
WebSocketConnectionAttemptsPerSec
WebSocketConnectionsAcceptedPerSec
WebSocketConnectionsRejectedPerSec
```

So either we will need to drop those metrics from the PR, or we'll need to figure out some way to only ask for them if the version is modern enough. Will need to think a bit about how to do that, though.

**Comment by jazzhanns** [comment]
I think we should keep those metrics versioned by IIS version if possible as it is a really useful feature for those who are running the later version to have (my production server, as it turns out, uses a later version of IIS (8.5) which is more critical for running this type of measurement than my test environment).

**Comment by martinlindhe** [comment]
I think exposing the metrics if newer IIS is enabled is also the way to go.
However, we need to figure out some details about software/OS detection.

Here is some powershell to query the IIS version. I couldn't find a pure WMI query for the same:
https://stackoverflow.com/a/16784626

**Comment by carlpett** [comment]
I agree that would be best. But the hard part about exposing the metrics depending on if they exist or not in this case is that we would need to have "conditional fields" on the struct [here](https://github.com/martinlindhe/wmi_exporter/pull/86/files#diff-99ebb317ad75faa6c7b80576a994e3aeR889), since the wmi library does reflection to build its query. Since we also need to match the name of the struct to the class, we can't have alternate structs depending on version either. There might be some trickery we can do of course, but it is not super-simple at least.

**Comment by jazzhanns** [comment]
Hi,

Do we have an update on this? Just wanted to make sure the PR doesn't fall below the radar!

Thanks :)

**Comment by carlpett** [comment]
Hi,
I'm unsure how to best proceed with this. The simplest way code-wise would be to disable all the new metrics on "older" systems (2008R2 and back). It doesn't feel very nice, but I don't really know what else to do, unless we want to either have different builds for different Windows verions (not very attractive), or just remove the metrics which didn't exist in the older versions.

**Comment by carlpett** [comment]
Ok, so now we can gate certain queries based on IIS version. The approach is to split such wmi classes into multiple structs, and use a new version of `wmi.CreateQuery` which allows to override the class name. 
@jazzhanns, when the CI has completed, could you verify that this works for you?

**Comment by jazzhanns** [comment]
Hi there, apologies for the late reply! Just ran that and am happy to report it appears to be working smoothly. 

Thanks!

**Comment by carlpett** [comment]
Nice, thanks!

**Pull request merged**
